-- Create a table to store daily solves
create table if not exists daily_leaderboard (
  id bigint generated by default as identity primary key,
  user_handle text not null,
  date date not null,
  solve_count int default 0,
  points int default 0,
  last_updated timestamptz default now(),
  
  -- Ensure one entry per user per day
  unique(user_handle, date)
);

-- Enable Row Level Security (RLS)
alter table daily_leaderboard enable row level security;

-- Create a policy that allows anyone to read
create policy "Public read access"
  on daily_leaderboard for select
  using ( true );

-- Create a policy that allows anyone to insert/update (for now, as we are doing server-side sync or client-side with anon key)
-- ideally this should be restricted to service role or authenticated users, but for this app's context:
create policy "Public insert/update access"
  on daily_leaderboard for insert
  with check ( true );

create policy "Public update access"
  on daily_leaderboard for update
  using ( true );
