-- Create a table to store daily solves
create table if not exists daily_leaderboard (
  id bigint generated by default as identity primary key,
  user_handle text not null,
  name text,
  date date not null,
  solve_count int default 0,
  points int default 0,
  last_updated timestamptz default now(),
  
  -- Ensure one entry per user per day
  unique(user_handle, date)
);

-- Safely add the name column if it doesn't exist (for existing tables)
alter table daily_leaderboard add column if not exists name text;

-- Enable Row Level Security (RLS)
alter table daily_leaderboard enable row level security;

-- Create a policy that allows anyone to read
drop policy if exists "Public read access" on daily_leaderboard;
create policy "Public read access"
  on daily_leaderboard for select
  using ( true );

-- Create a policy that allows anyone to insert/update
drop policy if exists "Public insert/update access" on daily_leaderboard;
create policy "Public insert/update access"
  on daily_leaderboard for insert
  with check ( true );

drop policy if exists "Public update access" on daily_leaderboard;
create policy "Public update access"
  on daily_leaderboard for update
  using ( true );
